"""Model definitions."""

from src.models.convnext_feature_backbone import (
    CONVNEXT_FEATURE_BACKBONE_TINY,
    CONVNEXT_FEATURE_TEST_BACKBONE,
    ConvNormAct,
    TinyFeatureBackbone,
)
from src.models.semantic_guided_cgaf import (
    SEMANTIC_GUIDED_CGAF_CONVNEXT_TINY,
    SEMANTIC_GUIDED_CGAF_TEST_BACKBONE,
    AsymmetricContextMixer,
    SegmentationGuidedSceneHead,
    SemanticGuidedCGAFCNN,
    SpatialContextGate,
    build_semantic_guided_cgaf_cnn,
)
from src.models.swin_transformer import (
    SWIN_SMALL,
    SWIN_TINY,
    SWIN_VARIANTS,
    SwinModelSpec,
    build_swin_classifier,
    build_swin_tiny_classifier,
)
from src.models.timm_classifier import (
    CONVNEXTV2_TINY,
    DINOV2_BASE,
    DINOV2_BASE_REG,
    DINOV2_SMALL,
    DINOV2_SMALL_REG,
    FOCALNET_SMALL_SRF,
    FOCALNET_TINY_LRF,
    FOCALNET_TINY_SRF,
    MOBILENETV4_SMALL,
    TIMM_MODEL_SPECS,
    TimmModelSpec,
    build_timm_classifier,
    get_timm_preprocess_settings,
    resolve_timm_model_name,
    slugify_model_name,
    trainable_parameters,
)

__all__ = [
    "SWIN_SMALL",
    "SWIN_TINY",
    "SWIN_VARIANTS",
    "SwinModelSpec",
    "CONVNEXTV2_TINY",
    "DINOV2_BASE",
    "DINOV2_BASE_REG",
    "DINOV2_SMALL",
    "DINOV2_SMALL_REG",
    "FOCALNET_SMALL_SRF",
    "FOCALNET_TINY_LRF",
    "FOCALNET_TINY_SRF",
    "MOBILENETV4_SMALL",
    "TIMM_MODEL_SPECS",
    "TimmModelSpec",
    "CONVNEXT_FEATURE_BACKBONE_TINY",
    "CONVNEXT_FEATURE_TEST_BACKBONE",
    "SEMANTIC_GUIDED_CGAF_CONVNEXT_TINY",
    "SEMANTIC_GUIDED_CGAF_TEST_BACKBONE",
    "AsymmetricContextMixer",
    "ConvNormAct",
    "SegmentationGuidedSceneHead",
    "SemanticGuidedCGAFCNN",
    "SpatialContextGate",
    "TinyFeatureBackbone",
    "build_semantic_guided_cgaf_cnn",
    "build_swin_classifier",
    "build_swin_tiny_classifier",
    "build_timm_classifier",
    "get_timm_preprocess_settings",
    "resolve_timm_model_name",
    "slugify_model_name",
    "trainable_parameters",
]
